package BlackJack2;

public enum ResultStates {
    WIN,
    DOUBLE_WIN,
    DRAW,
    LOSE,
    DOUBLE_LOSE,
    PLAYER_BLACKJACK,
    DEALER_BLACKJACK,
    DEALER_BLACKJACK_INSURED,
    DOUBLE_BLACKJACK_INSURED,
    PUSH,
    PLAYER_BUST,
    DEALER_BUST,
    DOUBLE_PLAYER_BUST,
    DOUBLE_DEALER_BUST,
    DEFAULT
}